name: main

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "26.x"
  CACHE_PATHS_BUILD: |
    ./website/build
  CACHE_KEY_BUILD: build-${{ github.sha }}-${{ github.ref_type }}

defaults:
  run:
    working-directory: ./website

jobs:
  build:
    name: Build 🏗️
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./website"

      - name: Install dependencies 🔧
        run: npm ci

      - name: Build 🏗️
        run: npm run build

      - name: Cache build ⚡
        id: cache_build
        uses: actions/cache@v6
        with:
          path: ${{ env.CACHE_PATHS_BUILD }}
          key: ${{ env.CACHE_KEY_BUILD }}

  lint:
    name: Lint ✅
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./website"

      - name: Install dependencies 🔧
        run: npm ci

      - name: Lint ✅
        run: npm run lint

  tsc:
    name: TypeScript Compiler 🔎
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./website"

      - name: Install dependencies 🔧
        run: npm ci

      - name: TypeScript Compiler 🔎
        run: npm run tsc

  deploy:
    name: Deploy 🚀
    needs: [build, lint, tsc]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: ${{ env.CACHE_PATHS_BUILD }}
          key: ${{ env.CACHE_KEY_BUILD }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: website/build
          clean: true
